### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Dogenator** [maximlarionov/goskulugi#2]
Can a more detailed description of how to apply this code? In python, the error "invalid syntax" gets out

**Comment by maximlarionov** [comment]
not really, authorship isn’t mine - I just launched the server, seems to be working, and that’s it.
Launched that with python 3.9 btw, if that might help.

also, there isn’t anything difficult, basically just a string generator from URL, which pasts those strings into template.

Best Regards,
Maxim Larionov
