### ISSUE TITLE
автор убейся

### ISSUE THREAD

**Issue by w3bsme** [maximlarionov/goskulugi#3]
зачем ты перезалил и собираешь звёздочки, скажи?

**Comment by Unope-Lab** [comment]
Ага, есть такое

**Comment by theowll** [comment]
**пососи хуя репа топ а ты говнот**

**Comment by maximlarionov** [comment]
@w3bsme ну, если вам важно звездочкодрочерство - могу сочувствовать. 
перезалил т.к. форки чистились по неймингу.

Какой-то сложности в подобной репе не вижу, держу ее открытой пока ДИТ не починит свои косяки на immune.mos.ru, поскольку получить QR даже при всех вводных могут не все.

**Comment by lgg** [comment]
@w3bsme ты убейся

а @maximlarionov живи долго и счастливо! <3
