### ISSUE TITLE
Последние цифры паспорта?

### ISSUE THREAD

**Issue by t3mp14r3** [maximlarionov/goskulugi#5]
![2021-07-04-23:41:12-screenshot](https://user-images.githubusercontent.com/38258346/124399039-9fd30c80-dd21-11eb-9239-9d4c28f8b604.png)

Не очень понимаю, что делать с последними цифрами паспорта, кажется, что нихера особо не выйдет.

**Comment by t3mp14r3** [comment]
По всей видимости придется дописать и эту часть с паспортом

**Comment by maximlarionov** [comment]
@t3mp14r3 Паспортные данные есть только на сертификатах вакцинировавшихся, и их QR кодах, на ПЦР к примеру их нет.

**Comment by t3mp14r3** [comment]
Хорошо, спасибо!
